### ISSUE TITLE
Compile issue with latest nextjs version (swc, not babel)

### ISSUE THREAD

**Issue by luatnd** [react-component/tween-one#131]
Hi, 
I use rc-tween-one with latest version of nextjs ("next": "12.0.7",) and get the compile error:

```
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/path/to/my-proj/node_modules/rc-tween-one/lib/plugin/PathMotionPlugin.js:10:48)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

error - SyntaxError: Cannot use import statement outside a module 
/path/to/my-proj/node_modules/tween-one/es/plugins/PathMotionPlugin.js:1
import _classCallCheck from "@babel/runtime/helpers/esm/classCallCheck";
^^^^^^
```

FYI, next@12 use swc instead of babel

### Reproduction steps
1. Create new next app
```
yarn create next-app --typescript
yarn add rc-tween-one
```
2. Use rc-tween-one:
pages/_app.tsx
```
import '../styles/globals.css'
import type { AppProps } from 'next/app'

//  ----> Add this line
import TweenOne from 'rc-tween-one';

function MyApp({ Component, pageProps }: AppProps) {

   // ----> Add this code
  return (
    <TweenOne
      animation={{
        x: 80,
        scale: 0.5,
        rotate: 120,
        yoyo: true, // demo 演示需要
        repeat: -1, // demo 演示需要
        duration: 1000
      }}
      paused={false}
      style={{ transform: 'translateX(-80px)' }}
      className="code-box-shape"
    />
  )
}

export default MyApp
```

### Expected behavior
Can compile and run it

Thanks

**Comment by lifegit** [comment]
hi, excuse me, have you solved it ?

**Comment by luatnd** [comment]
Not yet, I need to use this [template](https://github.com/ant-motion/landing-umi-example) from antd. 
it use babel

**Comment by ielireb** [comment]
You need to import it from the lib folder instead. 

```
// import TweenOne from "rc-tween-one";
import TweenOne from "rc-tween-one/lib/TweenOne";
```

[check out this sample code](https://codesandbox.io/s/nextjs-rc-tween-one-i6x9z?file=/pages/index.tsx)

**Comment by luatnd** [comment]
Many thanks, it's worked perfectly.

**Comment by hemanth12321** [comment]
@ielireb  Your solution works partially. I want to add ChildrenPlugin to tween-one which I do generally as `TweenOne.plugins.push(Children)`. But if I import it as `import TweenOne from "rc-tween-one/lib/TweenOne"` I can't use ChildrenPlugin

**Comment by jljsj33** [comment]
> @ielireb 您的解决方案部分有效。我想将 ChildrenPlugin 添加到 tween-one，我通常将其添加为`TweenOne.plugins.push(Children)`. 但是如果我导入它，因为`import TweenOne from "rc-tween-one/lib/TweenOne"`我不能使用 ChildrenPlugin

try `import ChildrenPlugins from 'rc-tween-one/lib/plugin/ChildrenPlugin';`

**Comment by hemanth12321** [comment]
@jljsj33 Importing ChildrenPlugin is fine. But to use ChildrenPlugin I need to do `TweenOne.plugins.push(ChildrenPlugin)`. But the `TweenOne.plugins.push(ChildrenPlugin)` won't work if I do `import TweenOne from "rc-tween-one/lib/TweenOne"`. Instead it works only if it is imported as `import TweenOne from 'rc-tween-one'` TweenOne.plugins.push(ChildrenPlugin)` works.

**Comment by pardhan03** [comment]
import TweenOneGroup from "rc-tween-one/lib/TweenOne";

Import it like this. This worked for me. I am using it in one of the Antd Component and I am facing the same issue.
